esphome/aioesphomeapi

aioesphomeapi/api.proto
aioesphomeapi/api_options_pb2.py
aioesphomeapi/api_pb2.py
aioesphomeapi/model.py

See also https://github.com/esphome/feature-requests/issues/12

Add sensor force_update option

---

README.rst
setup.py

Add README file

---

MANIFEST.in

Fixes https://github.com/esphome/aioesphomeapi/issues/16

Fix sdist requirements.txt missing

---

pylintrc
requirements_test.txt

Fixes #20
Also, helps for the Fedora RPM.

Unpin pylint

---

aioesphomeapi/api.proto
aioesphomeapi/api_pb2.py
aioesphomeapi/client.py
aioesphomeapi/model.py

This PR adds support for fan speeds expressed in percentages introduced in https://github.com/esphome/esphome/pull/1541

Add support for fan speed level

---

requirements_test.txt

See also https://github.com/esphome/aioesphomeapi/pull/22#issuecomment-863796813

Pin pylint again

---

aioesphomeapi/__init__.py
aioesphomeapi/client.py
aioesphomeapi/connection.py
aioesphomeapi/core.py
aioesphomeapi/host_resolver.py
aioesphomeapi/util.py
requirements.txt

Refactors the `host_resolve` module for zeroconf 0.32.0 and the new asyncio support: https://github.com/jstasiak/python-zeroconf#0320

Update host_resolve for zeroconf 0.32.0

---

MANIFEST.in
aioesphomeapi/client.py
aioesphomeapi/model.py

- Include py.typed file to indicate typing (see [PEP561](https://www.python.org/dev/peps/pep-0561/))
- Small fixes of types

Implement PEP561 typing support

---

.dockerignore
.github/dependabot.yml
.github/workflows/docker.yml
Dockerfile

I like to generate the files locally and so having a pre-built docker image helps with this =)

Build docker image to generate protoc

---

.github/workflows/docker.yml

This fixes ghcr empty manifest images

Use inline cache

---

.github/workflows/ci.yml
tests/test_client.py
tests/test_connection.py
tests/test_host_resolver.py

The script/lint script already did that, now adds that to CI too.

Also run black/isort on tests

---

README.rst

Remove loop argument

---

aioesphomeapi/_frame_helper.py
aioesphomeapi/connection.py

See also https://github.com/home-assistant/core/issues/65563#issuecomment-1033180478
The issue (or one of them) is that the handshake currently has no timeout, so if (for whatever reason) the ESP stops responding as seems to be the case here, the connect would hang forever.
I don't know _what_ is causing the socket to hang (the esp to stop responding); maybe the esp crashed/disconnected and we just didn't get the FIN packet (I don't know low level TCP that well); anyway, this safeguard should be there no matter what.
Additionally adds a safeguard for future similar problems, around the whole connect block

Fix no timeout for handshake

---

aioesphomeapi/connection.py

Reduces more instances of `Cannot send message because of TCP buffer space on the device` when streaming bluetooth advertisements
Watching debug logs for `aioesphomeapi` shows the messages coming in bursts instead of a few a time which makes it clear that the OS is buffering more of them so we can do fewer reads as well.

Increase underlying socket receive buffer

---

aioesphomeapi/connection.py

Fix permanent disconnect issue

---

aioesphomeapi/api.proto
aioesphomeapi/api_pb2.py
aioesphomeapi/model.py

- https://github.com/esphome/esphome/pull/3938

Get manufacturer name string from device

---

aioesphomeapi/client.py

Ensures the slot is recovered if the connection fails

Disconnect ble device if connect attempt fails to recover slot

---

aioesphomeapi/__init__.py
aioesphomeapi/client.py
aioesphomeapi/core.py

- Log error when connection timed out but already unsubscribed as its usually caused by a soft reset
- Log the address we were trying to connect to when there is a timeout
- Log a description of BluetoothGATTAPIError

Improve bluetooth error reporting

---

aioesphomeapi/client.py

We would wait for a response that would never come since we are writing without a response

Fix bluetooth write without response

---

aioesphomeapi/model.py

These are particularly hot paths so small optimizations matter here.

Small speed ups to the bluetooth advertisement converts

---

aioesphomeapi/connection.py

To further reduce the pressure on the esp, we want to read and drain the buffer as fast as possible, and since we have to wait to read while the data is processing we want the read loop to read as much as possible
first to keep the latency down and reduce the memory pressure on the esp.

Move message parsing out of the read loop

---

aioesphomeapi/_frame_helper.py
aioesphomeapi/connection.py

We still have a bit of latency with the reader because we have to lock and unlock every loop. Once we have finished the handshake (noise only) we hold the read lock for the duration of the connection to avoid locking/unlocking on every read

Optimize throughput of api to decrease latency

---

aioesphomeapi/model.py

fields has to be built every time its called even though it ever changes so put it behind a cache

Small speed up to parsing LE advertisement data

---

aioesphomeapi/connection.py

I think the original code had a small bug.

Only start task if existing one is done

---

aioesphomeapi/connection.py

Should help to determine the root cause of #341

Log the packet type when we get an invalid protobuf message

---

aioesphomeapi/client.py
aioesphomeapi/model.py

This is the only one we do 10000s (or more) of per hour so writing it out makes sense to make it faster as it avoids all the lookup/attr conversion

Speed up parsing/conversion of BluetoothLEAdvertisement

---

aioesphomeapi/_frame_helper.py
aioesphomeapi/client.py
aioesphomeapi/connection.py

https://github.com/esphome/aioesphomeapi/pull/352#discussion_r1063051688

Refactor cleanup to be a normal function

---

aioesphomeapi/connection.py

This is a small cleanup to make the `_cleanup` logic more similar to avoid future refactoring errors.

Clear on_stop after calling instead of using a separate `_on_stop_called` bool

---

aioesphomeapi/_frame_helper.py
aioesphomeapi/connection.py
requirements.txt
tests/test_connection.py

fixes #358
Some systems need the type conversion to `bytes`. In the grand scheme of things it doesn't really matter performance wise anyways.

Fix Invalid protobuf message: expected bytes, bytearray found and add coverage

---

aioesphomeapi/connection.py

It does not matter if we get back a PingResponse or any other message as we know the remote it alive and we should not cancel the connection because we think it is not responding
closes #400

Allow any message from the remote to cancel the pong timer

---

aioesphomeapi/_frame_helper.py

Remove unused lock from frame helper

---

aioesphomeapi/_frame_helper.py
aioesphomeapi/connection.py

related issue https://github.com/home-assistant/core/issues/92432

Fix disconnecting while handshake is in process

---

aioesphomeapi/connection.py

Small improvement that helps with BLE packet processing times

Avoid one dict lookup when processing packets

---

aioesphomeapi/_frame_helper.py

This is a small improvement for noise which avoids a dict lookup for every packet

Reduce lookups for noise in the frame helper

---

aioesphomeapi/connection.py

This reduces the overhead.
Discovered while working on #470

Simplify logic in send_message_callback_response

---

aioesphomeapi/connection.py

supports https://github.com/esphome/aioesphomeapi/issues/470

Reduce overhead to handle read exceptions

---

aioesphomeapi/connection.py

Reduce latancy when sending complex messages

---

aioesphomeapi/connection.py

This avoids constructing empty lambdas
related issue #470

Make do_append and do_stop optional in send_message_await_response_complex

---

aioesphomeapi/connection.py
tests/test_connection.py

Improve performance of processing incoming packets

---

aioesphomeapi/connection.py

Since we are already awaiting a future we can set a timeout exeception with a call_later instead of the overhead of async_timeout
related issue #470

Speed up timeout implementation in send_message_await_response_complex

---

aioesphomeapi/connection.py

Reduce overhead to send messages that need to wait for responses

---

aioesphomeapi/connection.py

Reduce overhead to send and process a complex message

---

aioesphomeapi/_frame_helper.py
aioesphomeapi/connection.py
tests/test__frame_helper.py

Reduces the number of round trips by one since
we can send the hello and the noise handshake
in the same packet

Speed up encrypted handshake

---

aioesphomeapi/_frame_helper.py

Reduce ChaCha20CipherReuseable overhead

---

aioesphomeapi/connection.py

- remove unneeded local var copy
- guard asserts with if TYPE_CHECKING
- remove unused pylint disables

Cleanup connection send_message from earlier refactoring

---

aioesphomeapi/client.py

The goal is to speed up HomeKit pairing
While #470 is solved for faster system, we still see some pairing timeouts with an RPI3b. 
We are running out of places where we can squeeze performance out to avoid the failures

Small speed up to bluetooth message wrapper

---

aioesphomeapi/client.py
aioesphomeapi/connection.py

#494 is actually a problem in core, but this is still a great cleanup

Cleanup bluetooth connection failure code

---

aioesphomeapi/_frame_helper/__init__.py
aioesphomeapi/_frame_helper/base.py
aioesphomeapi/_frame_helper/noise.py
aioesphomeapi/_frame_helper/plain_text.py
aioesphomeapi/client.py
aioesphomeapi/connection.py
aioesphomeapi/core.py
aioesphomeapi/host_resolver.py
aioesphomeapi/log_reader.py
aioesphomeapi/model.py
aioesphomeapi/reconnect_logic.py
aioesphomeapi/util.py

Our python_requires is set to 3.9+ which allows
using the newer typing

Upgrade python code to 3.9

---

aioesphomeapi/client.py
aioesphomeapi/connection.py
aioesphomeapi/reconnect_logic.py

cancel bugs are hard to find without messages, since we required py3.9+ we can add cancel messages

Add messages to all task cancels

---

aioesphomeapi/connection.py

`send_message_await_response_complex` could wait until the timeout if `disconnect` was called manually because `_read_exception_futures` were not resolved in this case. `_read_exception_futures` are now always resolved in `_cleanup`
On a fatal unexpected error, they did resolve correctly so this only happened when we didn't have a fatal error from something else.

Fix api calls not raising until timeout when the ESPHome device disconnects while waiting for a response

---

aioesphomeapi/connection.py

We now have two try blocks right next to each other from previous refactoring that can be combined

Reduce overhead to process packets

---

aioesphomeapi/connection.py

Fix failed disconnect requests not being logged

---

aioesphomeapi/client.py

We would recreate these dicts for every ESPHome device when they were always constant.  This happened on every deep sleep / reconnect as well

Make entity info and state mappings constants

---

aioesphomeapi/model.py

These get a bit expensive at startup when the services are downloaded from each BLE device.
In testing, the hit rate is almost 80%

Cache uuid conversions

---

aioesphomeapi/reconnect_logic.py

related issue https://github.com/home-assistant/core/issues/98221

Add additional connection logging

---

aioesphomeapi/connection.py

- There were a few places that could be cleaned up now that 3.9 is the minimum python version

Small cleanups to connection code

---

pyproject.toml

Adjust black target version to 3.9

---

aioesphomeapi/connection.py

OSError is an ancestor class of TimeoutError

Fix bad except clauses order

---

aioesphomeapi/connection.pxd
aioesphomeapi/connection.py

- When a device is offline we can spend a bit of time trying to connect over and over. The goal is to minimize the overhead

Small reduction in connect overhead

---

aioesphomeapi/connection.py

This is left-overs from previous refactoring

Remove unless local variable in _connect_resolve_host

---

aioesphomeapi/_frame_helper/base.py
aioesphomeapi/connection.py
tests/common.py
tests/test__frame_helper.py
tests/test_connection.py

related issue https://github.com/home-assistant/core/issues/102591

Fix unhandled exception when handshake times out

---

.github/workflows/release.yml

Build aarch64 wheels

---

aioesphomeapi/_frame_helper/plain_text.pxd
aioesphomeapi/_frame_helper/plain_text.py

Move the rare failure case into a new function

Small readability improvements to the plain_text frame helper

---

aioesphomeapi/_frame_helper/noise.pxd
aioesphomeapi/_frame_helper/noise.py

- add some more typing
- fix some bad var names

Small cleanups to noise write_packet

---

aioesphomeapi/_frame_helper/base.pxd
aioesphomeapi/_frame_helper/base.py
aioesphomeapi/_frame_helper/noise.pxd
aioesphomeapi/_frame_helper/noise.py
aioesphomeapi/_frame_helper/plain_text.pxd
aioesphomeapi/_frame_helper/plain_text.py
tests/test__frame_helper.py

protractor sends us `bytearray` where we expect `bytes`
related issue https://github.com/esphome/issues/issues/5117

Fix handling incoming data from protractor event loop

---

aioesphomeapi/_frame_helper/base.pxd
aioesphomeapi/_frame_helper/base.py
aioesphomeapi/_frame_helper/noise.pxd
aioesphomeapi/_frame_helper/noise.py
aioesphomeapi/_frame_helper/plain_text.pxd
aioesphomeapi/_frame_helper/plain_text.py
aioesphomeapi/reconnect_logic.py
tests/test__frame_helper.py

- reduce code to make this easier to test
- fix some try within try blocks

Refactor to reduce duplicate connection code

---

tests/common.py
tests/conftest.py
tests/test_connection.py

We didn't have any test coverage for pings, this adds coverage for it

Add tests for ping responses

---

tests/test_client.py

We didn't have any tests for button entities.

Add button tests

---

aioesphomeapi/client.py
tests/test_client.py

- add coverage for bluetooth gatt read and write

Reduce duplication in bluetooth gatt read code

---

aioesphomeapi/client.py

I'd like to get rid of these asserts, but we can't for now

Guard client connection asserts with if TYPE_CHECKING

---

aioesphomeapi/client.py

This is an internal change only to improve readability

Rename internal client connection get function to _get_connection

---

aioesphomeapi/client.py

I'm going to break up the client code a bit, this is the first step

Refactor state and service response converter to prepare to relocate code

---

aioesphomeapi/_frame_helper/noise.py

This is already checked in connection so we can never get here

Remove unreachable code in noise frame helper

---

aioesphomeapi/_frame_helper/noise.pxd

this is the same change as #692 but for noise (with the fix from #694)

Speed up noise frame helper

---

aioesphomeapi/_frame_helper/noise.pxd
aioesphomeapi/_frame_helper/noise.py

This was refactored away in a previous PR

Remove unused slot in the noise frame helper

---

aioesphomeapi/_frame_helper/base.pxd
aioesphomeapi/_frame_helper/noise.pxd
aioesphomeapi/_frame_helper/noise.py
aioesphomeapi/_frame_helper/plain_text.pxd
aioesphomeapi/_frame_helper/plain_text.py
aioesphomeapi/connection.pxd

- declare cdef functions that return nothing as void which avoids ref counting the result of these functions

Speed up frame helpers

---

aioesphomeapi/connection.py

This adds some more indent, but I almost removed a reachable one in #707 so I think its less refactoring risk

Reverse future done checks so we know they are actually reachable

---

tests/conftest.py

The test did not actually send the password but was mocking success

Add test for connecting with a password

---

aioesphomeapi/connection.py
tests/common.py
tests/conftest.py
tests/test_connection.py

- test for wrong api version
- test for wrong expected name

Add test for unexpected hello responses

---

aioesphomeapi/reconnect_logic.py
tests/test_reconnect_logic.py

There was an unconditional cancel of the connect task in the zeroconf path

Fix reconnect logic cancelling the connection while handshaking

---

.coveragerc
README.rst
aioesphomeapi/discover.py
setup.py

```
$ aioesphomeapi-discover
Status |Name                            |Address        |MAC         |Version         |Platform  |Board                           
------------------------------------------------------------------------------------------------------------------------
ONLINE |steamreset                      |192.168.214.27 |c82b9604a76a|2023.11.4       |ESP8266   |esp01_1m                        
ONLINE |icemaker                        |192.168.209.122|c82b96049bcb|2023.12.0-dev   |ESP8266   |esp01_1m           
```

Add discover cli tool

---

aioesphomeapi/client.py
tests/test_client.py

One more step closer to fixing https://github.com/esphome/aioesphomeapi/issues/764

Raise BluetoothConnectionDroppedError if connection drops during GATT read/write/notify

---

aioesphomeapi/client.py
tests/test_client.py

fixes https://github.com/esphome/aioesphomeapi/issues/764

Raise BluetoothConnectionDroppedError if connection drops while getting GATT services

---

aioesphomeapi/client.py
aioesphomeapi/client_callbacks.pxd
aioesphomeapi/client_callbacks.py

There is no self use here, it can move to the callbacks module

Refactor bluetooth message handling to extract on_bluetooth_message

---

tests/conftest.py
tests/test_client.py
tests/test_connection.py
tests/test_host_resolver.py
tests/test_log_runner.py
tests/test_reconnect_logic.py

This should allow us to merge https://github.com/esphome/aioesphomeapi/pull/813

Refactor tests for new pytest-asyncio

---

.gitignore

Gitignore the generated .c files for cython

---

.github/workflows/ci.yml
.pre-commit-config.yaml
requirements_test.txt
tests/common.py
tests/conftest.py
tests/test__frame_helper.py
tests/test_connection.py
tests/test_host_resolver.py
tests/test_log_runner.py
tests/test_model.py

We were formatting with ruff and black

Remove black from pre-commit

---

.github/workflows/docker.yml
Dockerfile
README.rst

Fix docker build following relocation of requirements_test.txt

---

.github/workflows/ci.yml
requirements/test.txt

Add missing timeout to tests

---

.github/workflows/ci.yml

ruff replaces what we used pylint for.
Also formatting was not being checked

Replace pylint with ruff in the CI

---

aioesphomeapi/_frame_helper/base.py
aioesphomeapi/_frame_helper/noise.py
aioesphomeapi/client.py
aioesphomeapi/connection.py
aioesphomeapi/discover.py
aioesphomeapi/host_resolver.py
aioesphomeapi/log_reader.py
aioesphomeapi/model.py
aioesphomeapi/util.py
pyproject.toml
setup.py
tests/common.py
tests/test_client.py
tests/test_model.py

Enable and fix some additional ruff checks

---

.github/workflows/release.yml

Its a bit nicer to have these on PyPI vs users having to use piwheels since we know we are going to need them

Build armv7l wheels

---

.github/workflows/release.yml

The last release added musllinux, add manylinux as well

Add manylinux armv7l wheels

---

.github/workflows/release.yml

This didn't cause any problems other than a display issue in actions

Fix benign extra curly brace in release CI

---

tests/conftest.py
tests/test_connection.py
tests/test_host_resolver.py

All the lingering timers and tasks have been fixed

chore: set verify_no_lingering_tasks fixture to autouse=True

---

aioesphomeapi/model.py
tests/test_client.py

#1080 added it to the protobuf, but I forgot to add it to the dataclass

Add `bluetooth_mac_address` to `DeviceInfo` model

---

setup.py

Compile with -g0 to reduce the size of the binaries

Reduce size of wheels

---

aioesphomeapi/_frame_helper/noise.pxd
aioesphomeapi/_frame_helper/noise.py
tests/test__frame_helper.py

Its about ~4% better of the decrypt path (note the benchmark includes the test overhead and encrypt overhead as well)

Reduce noise buffer copy overhead

---

aioesphomeapi/_frame_helper/plain_text.py

Reduce branching in plain text frame helper

Reduce branching in plain text frame helper

---

aioesphomeapi/connection.py

Rework process_packet to handle the common case of a single callback

Rework process_packet to handle the common case of a single callback

---

tests/test__frame_helper.py

I speculating on the cause of https://github.com/home-assistant/core/issues/142019 and was hoping I had an off by one  which caused the fault but after writing more tests I can't seem to find an issue here

Add more coverage for the frame helper

---

aioesphomeapi/_frame_helper/noise.pxd
aioesphomeapi/_frame_helper/noise.py
aioesphomeapi/_frame_helper/packets.pxd
aioesphomeapi/_frame_helper/packets.py
aioesphomeapi/_frame_helper/plain_text.pxd
aioesphomeapi/_frame_helper/plain_text.py
bench/raw_ble_plain_text.py
setup.py
tests/benchmarks/test_bluetooth.py
tests/common.py
tests/test__frame_helper.py
tests/test_connection.py

Usually I would split it into two modules here but each one has a load cost so I put it all in one

Split packet generation code into its own module

---

aioesphomeapi/connection.pxd
aioesphomeapi/connection.py

This is effectively the same thing as #1100 but for writing instead of reading

Avoid protobuf lookup to create messages

---

aioesphomeapi/connection.py

Most of the time there is a single one iterations of these loops so it doesn't make sense to hold a reference to the self object

Reduce some ref counting in the Cython version

---

.github/labeler.yml
.github/workflows/labeler.yml

Auto label pre-commit PRs

---

aioesphomeapi/log_parser.py
tests/test_log_parser.py

Optimize parse_log_message for single case

Optimize parse_log_message for single case

---

aioesphomeapi/connection.py

Ensure traceback is logged on unhandled exception during connect

Ensure traceback is logged on unhandled exception during connect

---

aioesphomeapi/host_resolver.py
tests/test_host_resolver.py

see title
fixes https://github.com/esphome/aioesphomeapi/issues/1337
none
Didn't add a test because that would require > 1 network interface on the test machine.

Fix scope_id in IPv6Sockaddr for "address%iface"

---

aioesphomeapi/connection.pxd
tests/test_connection.py

I missed we need to set the state directly in #1366

Fix failing tests when compiled with Cython
