- aioesphomeapi/model.py
Setting `cmp` has been deprecated and split into `order` and `eq`. Using `cmp=True` prints a warning. Both `order` and `eq` are `True` by default so we don't need to replace the `cmp=True` usage.
See also 19.2.0 changelog http://www.attrs.org/en/19.2.0/changelog.html#deprecations
> Remove cmp=True from APIVersion

- aioesphomeapi/util.py
Avoids executor overload on Home Assistant startup
2021-02-13 18:31:38 DEBUG (MainThread) [homeassistant.runner] Calling executor with function: <function getaddrinfo at 0x7f00184c8ca0>, args: ('10.45.211.201', 6053, <AddressFamily.AF_INET: 2>, 0, 6, 0), kwargs: {}
2021-02-13 18:31:51 DEBUG (MainThread) [homeassistant.runner] Calling executor with function: <function getaddrinfo at 0x7f00184c8ca0>, args: ('10.45.210.102', 6053, <AddressFamily.AF_INET: 2>, 0, 6, 0), kwargs: {}
2021-02-13 18:31:51 DEBUG (MainThread) [homeassistant.runner] Calling executor with function: <function getaddrinfo at 0x7f00184c8ca0>, args: ('10.45.211.180', 6053, <AddressFamily.AF_INET: 2>, 0, 6, 0), kwargs: {}
2021-02-13 18:31:51 DEBUG (MainThread) [homeassistant.runner] Calling executor with function: <function …
> Avoid a jump to the executor to validate an ip address string

- aioesphomeapi/model.py
See note at top of file:
```
```
The `default` arg is really just there for HA to be able to restore `info` items from the json storage.
For protobuf messages it's ignored because protobuf treats lack of a field as 0, and so when the instance is constructed it gets passed 0
> Fix bad default values in model

- aioesphomeapi/model.py
Fixes https://github.com/esphome/aioesphomeapi/issues/35#issuecomment-863252999
When the client responds with newer enum ints than `aioesphomeapi` knows, it results in an exception.
Change the behavior to instead set the property to `None` if the enum does not exist (not perfect for api design, because now everything needs to deal with `None` too - but I didn't find a good alternative).
Will need some changes in HA, so a draft for now.
> Safe enum conversion

- aioesphomeapi/client.py
Not sure how this happened, but the `Optional[LogLevel]` is throwing an error because LogLevel is not a type and isn't accepted by `Optional`.
```
File ".../aioesphomeapi/client.py", line 292, in APIClient
log_level: Optional[LogLevel] = None,
File "/usr/lib/python3.9/typing.py", line 268, in inner
return func(*args, **kwds)
File "/usr/lib/python3.9/typing.py", line 345, in __getitem__
return self._getitem(self, parameters)
File "/usr/lib/python3.9/typing.py", line 468, in Optional
arg = _type_check(parameters, f"{self} requires a single type.")
File "/usr/lib/python3.9/typing.py", line 157, in _type_check
raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: typing.Optional requires a single type. Got <google.protobuf.internal.enum_type_wrapper.EnumTypeWrapper object at 0x7f5f545e0940>. …
```
> Fix bad typing for LogLevel

- aioesphomeapi/model.py
In https://github.com/esphome/aioesphomeapi/pull/36 I renamed `type_` in UserServiceArg to `type` (to match what's in the protobuf definition).
Unfortunately, this rename meant that HA upgrades would have trouble restoring the services (assuming `bool` as the arg type), until the device reconnects; that's a minor annoyance at best, but we can still improve it easily.
> Dataclasses better legacy UserService compat

- aioesphomeapi/model.py
Fixes an issue with the field in proto and dataclass being different for the camera image.
Related: home-assistant/core#52718
Major bump as this is renaming the field
> Rename image field to data to match the proto field

- aioesphomeapi/client.py
Bug originally introduced here: https://github.com/esphome/aioesphomeapi/pull/36/files#diff-753f76689d07a39d2daa897bd6416dcb0546b60d15c3a944768fa4b8a75fd869L287
This fix fixed the protobuf->dataclass conversion: https://github.com/esphome/aioesphomeapi/pull/62/files but was incomplete.
For `on_state` we need to return the _merged_ data across the different image responses received.
Related: https://github.com/home-assistant/core/issues/52770
> Fix camera not merging packets

- .github/workflows/ci.yml
- .github/workflows/matchers/pytest.json
- README.rst
- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- aioesphomeapi/host_resolver.py
- aioesphomeapi/model.py
- requirements_test.txt
- script/lint
- setup.py
- tests/test_client.py
- tests/test_connection.py
- tests/test_host_resolver.py
- tests/test_model.py
- tests/test_util.py
After #62 and #63 I think it's good to have some unit testing in place.
This PR adds unit testing for most of the codebase except `connection.py` (code is hard to test) and `reconnect_logic.py`
Tests are currently only run on python 3.8+ (not 3.7) because they need [`unittest.mock.AsyncMock`](https://docs.python.org/3.8/library/unittest.mock.html#unittest.mock.AsyncMock) - future work might include backporting `AsyncMock` to also get test coverage with 3.7+
> Add pytest unit testing

- .github/workflows/protoc-update.yml
See failed run: https://github.com/esphome/aioesphomeapi/actions/runs/1079468748
The update workflow cannot run after release-drafter bumps the version
> Allow dispatching the protoc build workflow manually

- aioesphomeapi/model.py
ESPHome never supported this, and no built-in lights used this, but apparently it was used by third-party components. Without this fix, those lights would show up as on-off lights in HA. Make them RGBCT lights, which doesn't fit perfectly as they don't expect a white value, but they already had that in pre-2021.8 HA anyway and it's better than being totally broken.
> Fix old lights with color temperature but no white support

- aioesphomeapi/model.py
- aioesphomeapi/util.py
- tests/test_util.py
Noticed this with the number integration - took a bit to find out what's causing it, but here's a fix.
Basically, in esphome we send float values (and protobuf is told that too with the type). Unfortunately, single-precision floats don't exist in python and everything is double-precision.
So if we _send_ 0.1 to protobuf, it will convert that to a double-precision float (which it can do losslessly), but `((float) 0.1) != ((double) 0.1)` due to double being able to represent 0.1 closer.
Anyway, can be tested like this:
```yaml
number:
- platform: template
min_value: -90
max_value: 90
step: 0.1
optimistic: true
restore_value: true
initial_value: 42
```
Resulting HA state
```yaml
min: -90
max: 90
step: 0.10000000149011612
```
and then you can't enter anything because the HTML input thinks …
> Fix number rounding for protobuf messages

- aioesphomeapi/host_resolver.py
- aioesphomeapi/reconnect_logic.py
- requirements.txt
- tests/test_host_resolver.py
I want to switch esphome to use aioesphomeapi internally.
Unfortunately, that's currently not possible because aioesphomeapi requires zeroconf>=0.32.0, but esphome has it pinned at `0.28.8` at the moment (https://github.com/platformio/platformio-core/pull/3991)
So until PIO releases an update, we need to support older zeroconfs again
> Support for old zeroconfs

- aioesphomeapi/__init__.py
- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- aioesphomeapi/core.py
- aioesphomeapi/host_resolver.py
For the HA implementation of transport encryption I needed to differentiate between different connection error types (couldn't resolve address, requires encryption, etc). Previously this was checked by comparing the stringified error, but we needed a better solution.
Additionally add `_read_exception_handlers` so that exception that are thrown in the read loop are directly communicated to tasks waiting for a response (previously they would just wait until they time out, then notice the disconnect)
> Emit different Exception types to differentiate between connection errors

- aioesphomeapi/host_resolver.py
Similar to #26
Avoids executor overload at statup with lots of esphome devices
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.189, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.248, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.234, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at …
> Avoid executor jump to resolve ip addresses

- aioesphomeapi/host_resolver.py
Fixes the connection error under Windows : https://github.com/esphome/aioesphomeapi/issues/87
SOCK_STREAM is required anyways so make sure we get only SOCK_STREAM back from getaddrinfo
> fixes connection isssue#87

- aioesphomeapi/connection.py
Looks like I forgot to copy some code over from the noise implementation.
Specifically the try-except block for catching incomplete read errors is missing; it's responsible for catching incomplete read errors and converting it to SocketAPIErrors
> Fix plaintext logs unexpected when handled

- aioesphomeapi/connection.py
Small thing I missed in https://github.com/esphome/aioesphomeapi/pull/108
(Not found during testing because `_report_fatal_error` will set the error when reading the response, but still better to raise directly)
> Fix write_packet error not re-raised

- aioesphomeapi/connection.py
- tests/test_connection.py
A regression in https://github.com/esphome/aioesphomeapi/pull/108 :face_with_head_bandage: 
Some errors in the read task (among others, `RequiresEncryptionAPIError`) should _not_ be wrapped in `ReadFailedError`
Noticed this while looking into https://github.com/home-assistant/core/issues/56915 (note that the issue here is unrelated). The effect is that already _configured_ devices work fine, but setting up new ones doesn't because the appropriate exception isn't propagated to the config flow.
Side note: While we already do have more test coverage for model/client, the connection class does not. When I get time I will add some tests that would have caught this issue (should be easier now with the refactor)
> Fix wrapping native RequiresEncryption error types

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/connection.py
Small changes to exception handling to try and address an error seen a few times recently. Unable to do much beyond basic tests due complexity of reproducing :-( Error reproduced below.
Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/_frame_helper.py", line 68, in write_packet
await self._writer.drain()
File "/usr/local/lib/python3.9/asyncio/streams.py", line 387, in drain
await self._protocol._drain_helper()
File "/usr/local/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File …
> Catch conn reset

- aioesphomeapi/client.py
I have device with lots of sensors, I often get timeout error when loading initial data:
```
Error getting initial data for powermon2.local: Timeout waiting for response for <class 'api_pb2.ListEntitiesRequest'>
```
Even with good Wi-Fi signal, 5 seconds certainty not enough for devices with lots of sensors.
Even the `send_message_await_response_complex` function has default timeout of 10 seconds, what is the reasoning of short timeout for ListEntitiesRequest?
> Increase ListEntitiesRequest timeout to 30 seconds

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/connection.py
On my production system this eliminated 388 tasks being
created per minute.  async_timeout is what aiohttp uses
for timeouts since asyncio.wait_for has too much overhead.
> Change out asyncio.wait_for with async_timeout

- requirements.txt
Based on the history of commits #243 introduced a dependency on
async-timeout but missed adding it to the requirements.txt,
leading to exceptions when trying to use the module in a fresh
environment.
> Add async-timeout to requirements.txt

- aioesphomeapi/client.py
The default timeouts were shorter than the timeout used by bleak and the surrounding stack which could lead to unexplained timeout failures.
fixes #286
> Adjust ble timeouts to be longer than bleak timeouts

- aioesphomeapi/__init__.py
- aioesphomeapi/ble_defs.py
Not 100% sure this is the best place to put/format them, but seems better to live here than HA
Ideally we can provide a better error code than
`2022-10-25 09:42:33.737 DEBUG (MainThread) [bleak_retry_connector] VOCOlinc-VS1-185620 [E5:AB:B3:23:65:23] (id=E4:2F:25:E5:71:C5) - E5:AB:B3:23:65:23: Failed to connect: Error while connecting: 62, backing off: 0.1 (attempt: 2, last rssi: -62)`
`2022-10-25 09:42:47.406 DEBUG (MainThread) [bleak_retry_connector]  (D1:FB:3B:74:C8:90) - D1:FB:3B:74:C8:90: Failed to connect: Error while connecting: 19, backing off: 0.1 (attempt: 2, last rssi: -35)`
> Add esp ble error code mappings

- aioesphomeapi/client.py
We need to disconnect before raising the TimeoutAPIError to ensure the slot is recovered before the caller gets the exception and tries again
> Fix race while disconnecting after connect timeout

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
The GATT writes were not using the DEFAULT_BLE_TIMEOUT. When a HomeKit device pairs it can take a while to respond due to the encryption. We need to wait at least 30s
Also logs how long the timeout was when we raise
> Fix BLE writes timing out

- aioesphomeapi/connection.py
```
Task was destroyed but it is pending!
task: <Task pending name='Task-57' coro=<APIConnection._process_loop() running at /workspaces/aioesphomeapi/aioesphomeapi/connection.py:534> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object APIConnection._process_loop at 0x7f784a916110>
Traceback (most recent call last):
File "/workspaces/aioesphomeapi/aioesphomeapi/connection.py", line 534, in _process_loop
msg = await self._to_process.get()
File "/usr/local/lib/python3.10/asyncio/queues.py", line 161, in get
getter.cancel()  # Just in case getter is not done yet.
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
self._check_closed()
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
raise …
```
> Catch error when task is stopped

- aioesphomeapi/client.py
If we try to connect again and we do not wait for the disconnected event to happen
the esp will fail to try to connect again
See https://github.com/espressif/esp-idf/issues/5105
> Wait for BLE disconnect when connecting timeouts

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
If the connection attempt was canceled the message callback subscription would leak.
fixes #315
> Fix connection subscription leak on cancelation

- aioesphomeapi/client.py
I do not think there is any harm in increasing this timeout. This helps when a single ESPHome device has very many entities.
> Increase timeout while waiting for ListEntities to be done

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/util.py
Since each message must be at least 3 bytes we now try to read the the first 3 bytes intead of 1,1,1.  We only do additional reads when the message type or length exceeds 1 byte.
This reduces the number of readexactly calls
Went from 25000 to 9000 per minute so nice improvement
> Reduce number of calls to readexactly

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- aioesphomeapi/model.py
- tests/test_client.py
~~Needs https://github.com/esphome/aioesphomeapi/pull/327~~
Previously every listener had to get every bluetooth advertisment message and than reject it.  Refactor subscribing to message types so we only get callbacks for message types we want so every callback does not need to reject messages it doesn't want (ie bluetooth advs)
This was particularly slow when with a lot of gatt notifies setup because it had to callback each one and reject (which later turned out to be even worse because of a leak https://github.com/esphome/aioesphomeapi/pull/329)
> Callback messages to listeners by type

- aioesphomeapi/client.py
`bluetooth_gatt_start_notify` would leak since there was no way to cancel it when the device disconnected. This lead to a build up of notify callbacks over time. Since all listeners have to reject each callback this made the code slower and slower as each notify listener was built up until the system became sluggish from 1000s of notify callbacks that had to be enumerated and rejected
Needed for https://github.com/home-assistant/core/pull/83106
https://github.com/esphome/aioesphomeapi/pull/328 refactors to prevent the linear searching of callbacks
BREAKING CHANGE: `bluetooth_gatt_start_notify` has changed:
Returns two functions that can be used to stop the notify.
The first function is a coroutine that can be awaited to stop the notify.
The second function is a callback that can be called …
> Add method to cancel bluetooth_gatt_start_notify upon ble device disconnect

- aioesphomeapi/_frame_helper.py
related issue https://github.com/home-assistant/core/issues/83212
If the esp crashes and reconnects we will get a ConnectionResetError since we will still be holding the connection to the esp when it went offline. When it comes back up it will send a RST when we try to talk to it again after it soft reset since we are talking over a connection it thinks is closed.  This only happens if it reboots and comes back up before we timeout from the ping failing 
hopefully the crash that was triggering this is fixed in https://github.com/esphome/esphome/pull/4140
> Handle socket reset errors while reading

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- aioesphomeapi/model.py
- aioesphomeapi/util.py
- tests/test__frame_helper.py
- tests/test_client.py
- tests/test_connection.py
This  removes ~ 20k `call_soon`s per minute which translates to a significant latency improvement (also reduces the run time by ~ 18-24%) with 7 ble proxies.
With this change we can refactor a significant number of coroutines into normal functions.
Eliminates:
- read_loop
- process_loop
- queue
Data now comes in via `data_received` and is called back to the packet processor which was the original `process_loop` and than called back to the consumers of the API (HA) and than to each integration which eliminates the overhead of having to put it into a queue, pull it out of a queue, schedule, fire, etc which was usually more expensive than parsing (when using cpp protobuf) and processing the data itself since almost everything coming from esphome are tiny packets of data (with high frequency …
> Simplify connection flow with an asyncio.Protocol

- aioesphomeapi/connection.py
- aioesphomeapi/reconnect_logic.py
https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task
> Important Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done. For reliable “fire-and-forget” background tasks, gather them in a collection:
see https://github.com/python/cpython/issues/88831
> Ensure we hold strong references to tasks

- aioesphomeapi/client.py
fixes an issue when a disconnect is followed by a connect, example:
```python
def connect_cb(connected, ...)
print("Connected:", connected)
await api.bluetooth_device_disconnect(...)
await api.bluetooth_device_connect(..., connect_cb)
print('Attempt to use connection')
```
yields
```
Connected: False
Attempt to use connection
Connected: True
```
`bluetooth_device_disconnect` resolves as soon as the aioesphomeapi call is done which I think is fine but it is unexpected to have a closed connection after an `await bluetooth_device_connect`.
> Fix bluetooth_device_connect returning prematurely from a disconnect

- aioesphomeapi/connection.py
There was a small race window were we would be setting up the connection during the disconnect request that would have prevented the esp from seeing that the client was disconnecting. It would eventually get cleaned up by the keep-alive timeout on the esp side.
> Fix disconnect message not being sent when disconnecting during hello phase

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- aioesphomeapi/reconnect_logic.py
- tests/test_connection.py
If the esp gets an OTA or requests a disconnect because its rebooting, we would reconnect too quickly before the device had shutdown accepting socket connections and end up trying to talk to a device that was moments away from rebooting which would delay reconnecting once the device came back up
> Cooldown before reconnecting on expected disconnect

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
Refactor keep alive to avoid coroutines which makes cancelation and disconnect a lot simpler since we don't have to worry about the complexity of canceling a task.
The ping pong timeout was 10s with a send frequency of 15s. This change increases the keep alive frequency to 20.0s and raises the default no response timeout to be 90s (4.5x the keep alive frequency). 20s was chosen because its about the time it takes for the esp device to reboot and reconnect to the network.
This helps devices that may not have the best connection or are using some type of wifi power management aka `power_save_mode: LIGHT`.
The timeout is slightly more half of the time in the esphome code base, https://github.com/esphome/esphome/blob/df3f13ded884682dfbcbba542d79aedb1e100b0a/esphome/components/api/api_connectio …
> Adjust ping timeout to prevent premature disconnections

- aioesphomeapi/model.py
- setup.py
UUID conversions are a red hot execution path because of the number of BLE advertisements
`_convert_bluetooth_le_service_uuids` and `_convert_bluetooth_le_service_data` drop off the profile with this change
The hit rate on these is stellar since many proxies can mean upwards of 10000-25000 uuids conversions per minute even with only passive scans. With active scans we can reach 50/s per proxy
```
2023-04-04 23:55:51.124 CRITICAL (SyncWorker_5) [homeassistant.components.profiler] Cache stats for lru_cache <function _uuid_converter at 0x7fcd0976d5a0> at /usr/local/lib/python3.10/site-packages/aioesphomeapi/model.py: CacheInfo(hits=4996, misses=13, maxsize=1024, currsize=13)
2023-04-04 23:56:35.448 CRITICAL (SyncWorker_18) [homeassistant.components.profiler] Cache stats for lru_cache …
```
> Reduce uuid conversion overhead

- aioesphomeapi/model.py
This was only used in one place. I had originally had more code in it but I did not think to collapse it when I removed the code since it turned out to be smaller expected.
I only noticed because I had to turn on active scans to test something else and it was called 30000/min
> Remove _convert_bluetooth_le_name as it did not need to be its own function

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/connection.py
- tests/test__frame_helper.py
Wrapping everything up in a simple dataclass and than unwrapping it per packet when processing 10000 per minute added a lot of run time and complexity.
As previous refactoring made the data simpler the wrapper for the raw bytes, which was only used internally, added some unneeded complexity.
> Improve data throughput

- aioesphomeapi/model.py
- setup.py
The goal is to reduce the memory overhead of these objects since we have a lot of them floating around.  (10k/min on some of my production installs)
I also removed the APIModelBase because nothing is checking for it and we can avoid the `__post_init__` override. Since most of the data is `dict`s/`list`s which can be modified it did not make sense to pay the cost of frozen since it is not actually protecting the data
https://docs.python.org/3.9/library/dataclasses.html#frozen-instances
This is roughly a 15% speed up as well
> Use sloted dataclass for BluetoothLEAdvertisement

- aioesphomeapi/client.py
`start_task` has a reference in `unsub` which the caller holds
`stop_task` did not have a strong reference. To prevent it from being garbage collected its now held in background tasks
https://github.com/esphome/aioesphomeapi/pull/412/files#r1162523622
> Hold strong references to voice assistant tasks

- aioesphomeapi/model.py
Since we only ever convert these from protobuf we can reduce the branching and collapse the conversion functions.
The bytes recopy is now avoided in the dict comps.
Will run this on production for a while to be sure
Processing these is still the largest time for all the esphome code.
This works out to ~17% speed up
> Reduce overhead to process bluetooth advertisements

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/connection.py
- aioesphomeapi/core.py
- aioesphomeapi/reconnect_logic.py
- tests/test__frame_helper.py
see https://github.com/home-assistant/core/issues/94663
- Fix encryption error being overridden by another exception
- Fix encryption error not being raised because cleanup fails with a different exception which overshadows it
- Ensure that an exception during an asyncio.Protocol callback is reported upward by switching from an event to a future
- Backoff to maximum time on password or encryption error as we do not want to keep hammering the device if the reason we cannot connect is auth
> Fix more cases where incorrect encryption keys were not detected

- aioesphomeapi/_frame_helper.py
- requirements.txt
Using noise currently incurs a performance penalty (enough that not using it is sometimes a understandable reason). It's a bit uncomfortable being in a position of having to ask users to turn off noise because they have so many esphome devices that it's overwhelming their ha running on raspberry pi (eof errors, connection drops, etc). The goal is to get that penalty closer to zero to eliminate any reason not to use noise (if only eap8266 had just a bit more ram we ... but that's a another issue).
chacha20poly1305-reuseable is a faster drop-in replacement version of chacha20poly1305 which does not use the thread locking that the cryptography base implementation uses since asyncio does not need the ability to encrypt/decrypt in different threads.
Home Assistant currently uses …
> Speed up noise by using chacha20poly1305-reuseable

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/core.py
HA cannot figure out which device to get from the dashboard without the server name if we only have the IP
The pattern in HA needs to change to
get_device_info ->fails with needs encryption key 
try again with encryption key or empty one
Get device name
get name from dashboard
get key
try again
> Include the server name in the exception for invalid encryption key

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- tests/test_connection.py
This is a small performance improvement since we do so many callbacks to access self 
The tests have been refactored to avoid patching the client or connection anymore to get a better end to end test
> Use slots for APIConnection and APIClient

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/util.py
- tests/test__frame_helper.py
- Unpack protocol bytes into named values: Easier to see what the data is and uses unpacking sequence which is fast
- For small packets we avoid calling `bytes_to_varuint`
- Avoid a lot of memory copy
- Avoid multiple calls to get length in places it cannot change
- Decryption errors are now raised instead of causing the protocol to fail (its still going to drop but we get the right exception now)
Works out to ~24-38% faster on average
> Reduce protocol overhead

- aioesphomeapi/client.py
Save the camera data in a list of memory views and join them all together when we have the final packet. This avoids creating a new bytes object every time the camera sends a partial response
> Use memoryview for camera images

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/connection.py
We want to avoid formatting data for debug when
debug is not enabled since a camera stream will
continually write requests to keep the stream
alive
> Add checks for debug logging in the write path

- aioesphomeapi/_frame_helper.py
- tests/test__frame_helper.py
The camera packets tend to get fragmented because of the size and I was looking for a bug in the reassembly but it turns out the camera was just overheating.
I thought there was a bug here but there isn't after I wrote the tests it shows it works as expected. However the new design is faster so I'll clean it up and move it forward
- Avoid checking `len()` each read call
- Remove some unreachable checks since the decryption will fail if the data is invalid
- Remove a useless shift
- Avoid the extra stack depth of `_callback_packet` since it was only called from one function
> Improve performance reassembling fragmented packets

- aioesphomeapi/client.py
- aioesphomeapi/model.py
This is part of an effort to reduce latency to see the BTHome buttons since I noticed there was a bit of latency when testing
Avoids making a dataclass of `BluetoothLERawAdvertisements` that is immediately thrown away since the `client` wants a list of `BluetoothLERawAdvertisement` dataclasses and never sees `BluetoothLERawAdvertisements`
Rename everything using `on_msg` to a name that reflects what type of message is being processed to improve trace and profile discoverability
> Improve performance of converting raw BLE advertisements

- aioesphomeapi/connection.py
This is the same optimization that the ESPHome side has
https://github.com/esphome/esphome/blob/ddde1ee31ef96476c7a7d1c8b8fe306aa4d2e503/esphome/components/api/api_connection.cpp#L119
The goal is to keep network traffic to a minimum and avoid radio time when not needed
> Avoid sending pings when we have traffic

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/connection.py
- tests/test__frame_helper.py
- tests/test_connection.py
Its not clear what is wrong when the device gets re-flashed without encryption but HA is still requesting it.
This PR improves the error reporting
> Improve error reporting when encryption is disabled on device but client requests it

- aioesphomeapi/client.py
There were some isinstance checks that can never be false
> Guard a few frequently called instance checks with if TYPE_CHECKING

- aioesphomeapi/_frame_helper.py
fixes #476
```
% python3 timer.py
0.045173624996095896
0.07660245802253485
```
```
import timeit
from functools import partial
from struct import Struct
PACK_NONCE = partial(Struct("<LQ").pack, 0)
def call2(n: int):
return b"\x00\x00\x00\x00" + n.to_bytes(length=8, byteorder="little")
print(timeit.timeit("call(1)", globals={"call": PACK_NONCE}))
print(timeit.timeit("call2(1)", globals={"call2": call2}))
```
> Speed up formatting the cipher nonce

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
If we failed during getting device info vs another request is was not clear if it was an auth problem or not from the message
> Improve error reporting for authenticated vs non-authenticated requests

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- Use a future instead of an Event so we can simplify the timeout procedure
- `remove_message_callback` can now be abstracted away so the client does not ever have to know about it anymore since everything that subscribes now returns a callback to unsubscribe which reduces the risk we will get it wrong and leak subscribers
> Speed up BLE connections

- aioesphomeapi/_frame_helper.py
- aioesphomeapi/connection.py
- tests/test__frame_helper.py
- tests/test_connection.py
If _send_pending_ping was set to False we would still check for pong which was incorrect as it should be skipped until the next time a ping is due
I cleaned up the logging to make sure the name of the device is always logged as I thought this was working correctly but I was getting devices confused
> Fix pong timer warning when pending ping is skipped

- aioesphomeapi/client.py
In #456 these the camera bytes were wrapped in memoryview but since the memory is not contiguous the final string has to copy anyways which makes overhead of wrapping in a memoryview is useless and counterproductive. The real speed up was not building a new bytes string every message and the cost of wrapping the memoryview was so small that I did not notice it was ineffective
> Remove memoryview wrapping for cameras

- aioesphomeapi/connection.py
- Make the connect process a bound method to avoid closure construction every time we connect (small imporvement for devices that disconnect/reconnect frequently due to wifi or deep sleep)
- remove api_version property since it does not need to be protected as the class is only used internally
- add OPEN_STATES = {ConnectionState.SOCKET_OPENED, ConnectionState.CONNECTED} constant to collapse some duplicaiton
> Cleanups to connect process

- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/_frame_helper/plain_text.py
- aioesphomeapi/connection.py
- tests/test__frame_helper.py
- tests/test_connection.py
- Remove the need to a connected event and a separate future. The ready future is now used by both noise and plaintext
- Fixes the double timeout with noise and now allows the timeout to be set from the caller
fixes #499
> Refactor frame helpers to share more code

- aioesphomeapi/connection.py
We should still try to send the DisconnectRequest to the ESP device when we do a forced_disconnect, but we should not wait for it to respond
> Fix not trying to disconnect cleanly on forced disconnect

- aioesphomeapi/connection.py
Since send_message_await_response_complex was refactored to always return on the first response, this check is now impossible
fixes #509
> Remove impossible check in send_message_await_response

- aioesphomeapi/connection.py
It was hard to figure out what was going wrong because we only logged the received_name and not the expected name
fixes #508
> Fix BadNameAPIError to include the expected name

- aioesphomeapi/connection.py
Increase SO_RCVBUF to 2MiB to reduce chance of ESP32 cam disconnects
```
Logger: aioesphomeapi.connection
Source: runner.py:179
First occurred: 1:56:01 AM (65 occurrences)
Last logged: 8:40:21 AM
cam-utilities-indoor @ 192.168.210.41: Connection error occurred: cam-utilities-indoor @ 192.168.210.41: EOF received
```
> Increase SO_RCVBUF to 2MiB to reduce chance of ESP32 cam disconnects

- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- aioesphomeapi/reconnect_logic.py
- Only call `loop.time()` once in the ping path (`call_later` has to fetch time under the hood)
- Avoid `call_later` and use `call_at`
> Avoid a few calls to fetch loop time

- aioesphomeapi/reconnect_logic.py
fixes #537
before
```
2023-09-05 18:03:34.850 DEBUG (MainThread) [aioesphomeapi.reconnect_logic] disco @ 192.168.211.119: Triggering connect because of received mDNS record record[ptr,in,_esphomelib._tcp.local.]=4500.0/4500,disco._esphomelib._tcp.local.
2023-09-05 18:03:34.851 DEBUG (MainThread) [aioesphomeapi.reconnect_logic] Removing zeroconf listener for disco
2023-09-05 18:03:34.851 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework …
```
> Fix zeroconf listener being removed from zeroconf callback

- aioesphomeapi/host_resolver.py
- tests/test_host_resolver.py
replaces `addresses_by_version` with `ip_addresses_by_version` as `addresses_by_version` was deprecated in zeroconf 0.53 and `addresses_by_version` was broken in newer zeroconf until it was recently fixed in zeroconf 0.115.1
related issue https://github.com/home-assistant/core/issues/101039
> Switch host resolver to use modern zeroconf APIs

- .github/workflows/ci.yml
- aioesphomeapi/connection.py
- tests/test_connection.py
pylint showed us some bugs hiding out in https://github.com/esphome/aioesphomeapi/pull/565 because we weren't running tests on newer python
All the linters will only run on py3.11 since py3.12 is not ready yet
> Run tests on multiple python versions

- .github/workflows/ci.yml
- README.rst
- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
- aioesphomeapi/connection.py
- pyproject.toml
- setup.py
- tests/test_connection.py
The frame helper is where most of the overhead is for processing incoming packets now that we are using the upb implementation of protobuf.
Since we process 1000s of bluetooth packets per minute, the overhead of python shipping around and decoding the bytes can be a bit high.
This adds an optional cython extension to target the hot areas of the code.  I only bothered with receiving data as I don't know if there is a use case for high volume sending (if there is we can optimize that in another pass).
If cython is not available, the build script will not cythonize and install the pure python version.
> Add optional basic cython implementation for frame_helper

- .github/workflows/release.yml
We don't support py<3.9
Don't try to build wheels one them
> Disable wheel builds on old pypy versions as well

- aioesphomeapi/connection.py
- requirements.txt
`asyncio.timeout` is preferred over `async_timeout` now that its part of stdlib
> Remove async_timeout requirement on python 3.11+

- .github/workflows/release.yml
We do not use pypy for any esphome images and having them doubles the build time.
> Disable all pypy wheels

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
This moves all the frame helper buffer management complexity into the base class
so its not reimplemented in plain_text and noise
Most of the time we do not have to buffer so we can hold
the bytes object and read the packet out of it instead
of having to copy it.
This is roughly a ~22% speed up processing the incoming bytes
in the frame helper.
This is another attempt at https://github.com/esphome/aioesphomeapi/pull/544#issuecomment-1712100612
> Reduce memory copy when buffering is not required

- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- tests/test_connection.py
This is an internal change only
This avoids the overhead of having to figure out how to iterate these every time, and since they are already always tuples, we can change the typing from Iterable to tuple to be more narrow
> Narrow msg_types to only accept tuples

- aioesphomeapi/client.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- aioesphomeapi/core.py
- aioesphomeapi/reconnect_logic.py
- tests/test_client.py
- tests/test_connection.py
Note: this isn't a breaking change for anything using the ReconnectLogic, but I figure someone might be calling the connection logic directly so I tagged it a major.
If the first connect fails, we now keep the zeroconf listener going and will cancel any in-flight connection attempts as soon as the device announces it online to mdns. This restores the connection logic to how is used to be before we did some fixes for races which prevented reconnecting from working sometimes. This version should not suffer from the same problem, and still retain the faster reconnects because it splits up the connection logic to be safer.
To accomplish this the connection process is now split into two parts:
start_connection and finish_connection
- start_connection is intended to be able to be safely …
> Split connection process to enable faster reconnects

- aioesphomeapi/client.py
- aioesphomeapi/reconnect_logic.py
- tests/test_reconnect_logic.py
We have three places that log the name:
- reconnect_logic
- connection
- client
The goal it to make them all the same
since various callers pass the name
in different ways to preserve compat
> Improve consistency of name logging

- aioesphomeapi/host_resolver.py
- tests/test_host_resolver.py
The logic in the host resolver would call `_async_ip_address_to_addrs` even when we knew the host was not an ip address. `_async_ip_address_to_addrs` does not do any dns resolution so passing in a hostname to it will always return an empty result
> Fix trying to convert hostnames to IP Addresses

- aioesphomeapi/model.py
- tests/test_model.py
Note that we include the entity info type in the unique id. Normally HA does not need this but since esphome platforms to not directly map to HA platforms (ie sensor and text_sensor), we must include it.
> Add function to build new format unique ids

- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
- aioesphomeapi/util.py
- tests/test__frame_helper.py
- tests/test_util.py
These are only used in the plain_text frame helper.  When I split up the frame helpers I forgot to move them.
> Move varuint functions into plain_text frame_helper

- aioesphomeapi/__init__.py
- aioesphomeapi/client.py
- aioesphomeapi/model.py
These used to be a lot more complex, and we can remove the make_ble_raw_advertisement_processor
> Simplify raw ble advertisements callbacks

- aioesphomeapi/reconnect_logic.py
- tests/test_reconnect_logic.py
- When the state machine changed state we did not always check that we held the lock. We now do to ensure we avoid future regressions
- This did not uncover any existing bugs. The goal it to make the implementation safer against future refactoring
> Make reconnect logic state machine switches check locks

- aioesphomeapi/connection.py
We had two ways of handling incoming packets:
- dispatch via registered handlers
- hard coded list of handlers
To simplify the handling of incoming packets we now register the internal handlers which leaves a single dispatch path for processing packets
> Refactor internal message handlers to use a single dispatch path

- aioesphomeapi/connection.py
- tests/test_connection.py
The cleanup code would not close the frame helper if the handshake failed because it was set too late
Fixes `RuntimeError: File descriptor X is used by transport` when the handshake raises
fixes https://github.com/home-assistant/core/issues/102591
> Ensure frame_helper is always closed before the underlying socket

- aioesphomeapi/connection.py
- tests/test_connection.py
- Use the name of the request type that was sent instead of the raw class as its more readable
- Adds some more missing coverage
> Improve logging on clean disconnect failure

- aioesphomeapi/connection.py
- tests/test_connection.py
The tasks have been auditted to ensure they have proper timeouts, remove the extra ones that were added when we were not sure the connect tasks had the right timeouts
closes #606
> Remove extra timeouts

- aioesphomeapi/reconnect_logic.py
- tests/test_reconnect_logic.py
- Trigger on A record updates since they happen more often
- Fix logic reversal in accept_zeroconf_records
fixes https://github.com/home-assistant/core/issues/103517
> Fix zeroconf reconnect logic

- aioesphomeapi/reconnect_logic.py
- tests/test_reconnect_logic.py
There was a very rare race where we could disconnect in the middle of the handshake if we had just finished connecting to the ESP which would prevent the disconnect request from being seen by the ESP
To fix this we now only cancel without the lock if we are still establishing the connection, otherwise try to wait for the handshake to finish so we can cleanly disconnect.
This didn't cause any visible issues besides a log message on the esp
> Wait for handshake to finish to allow for clean disconnect when stopping reconnect logic

- aioesphomeapi/reconnect_logic.py
- tests/test_reconnect_logic.py
#614 fixed the case were we would cancel the handshake in progress, but it did not account for the race where we have not switched the state to connecting yet because we have not obtained the lock. While I could only get this to happen in a test its likely it possible in the real world if the timing is exactly perfect
> Allow the stop callback to be cancelled when already disconnected

- .github/workflows/release.yml
This change is only to decrease the time it takes to do a release and save space on PyPI. The release time is > 45 minutes because of the addition of aarch64 wheels which have to be done in qemu since github doesn't have native arm runners.
When esphome 2023.11.0 is released, the containers will be python 3.11 based so we will no longer need wheels for old python versions.
This does not increase the library minimum python version and wheels can still be built locally for older python versions.
> Stop building wheels for python 3.9/3.10

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- tests/common.py
- tests/test_client.py
- tests/test_reconnect_logic.py
Consumers of the api may pass string like objects that are not actually python `str` objects.  Since `expected_name` and `noise_psk` are strongly typed to `str` in `APIConnection` to allow fast string operations, we ensure they are actual `str` objects before passing them from `APIClient` to `APIConnection`
related issue https://github.com/esphome/issues/issues/5090
> Ensure passed params are always a str

- aioesphomeapi/client.py
- tests/test_client.py
HA passes `` when these values are `None`
> Ensure an empty noise_psk or expected_name is treated as None

- aioesphomeapi/client.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- aioesphomeapi/reconnect_logic.py
- tests/test_client.py
- tests/test_connection.py
Current we send HelloRequest, wait for a response, than send ConnectRequest and wait for a response.
We can send the `HelloRequest` and `ConnectRequest`, and than wait for both responses instead as it reduces one round trip wait. 
This should speed up connecting with encryption enabled a little bit since it reported to be slow in https://github.com/home-assistant/core/issues/103517#issuecomment-1798017912
```
INFO Starting log output from largegarage.local using esphome API
INFO Successfully connected to largegarage in 0.061s
INFO Successful handshake with largegarage in 0.022s
[18:45:21][I][app:102]: ESPHome version 2023.11.0b2 compiled on Nov  8 2023, 23:13:11
```
```
INFO Starting log output from icemaker.local using esphome API
INFO Successfully connected to icemaker in 0.020s
INFO …
```
> Send hello and login asynchronously to speed up connecting

- .coveragerc
- aioesphomeapi/log_reader.py
- aioesphomeapi/log_runner.py
- setup.py
- tests/common.py
- tests/conftest.py
- tests/test_connection.py
- tests/test_log_runner.py
The entry point was missing from `setup.py` so the `aioesphomeapi-logs` script was never created
> Make log runner code reusable and add coverage

- aioesphomeapi/log_reader.py
- aioesphomeapi/log_runner.py
- tests/common.py
- tests/test_log_runner.py
The log runner was using the sync close function instead of the async one
> Ensure zeroconf instance is closed when log runner ends

- .github/workflows/release.yml
Home Assistant is already going to build these anyways for the wheel builder so its unlikely these are actually be used
> Avoid building musllinux wheels

- aioesphomeapi/log_reader.py
I'm trying to figure out why there is a three second delay when connecting with noise
It seems the handshake finishes rather quickly but it can't read the first encrypted packet from the api for ~3s
```
[22:07:37][D][api.connection:181]: aioesphomeapi (192.168.209.204) requested disconnected
[22:07:37][VV][api.service:031]: send_disconnect_response: DisconnectResponse {}
[22:07:37][V][api:115]: Removing connection to aioesphomeapi
[22:07:38][D][api:102]: Accepted 192.168.209.204
[22:07:38][VV][api.socket:696]: 192.168.209.204: Handshake complete!
[22:07:38][W][component:214]: Component api took a long time for an operation (0.36 s).
[22:07:38][W][component:215]: Components should block for at most 20-30ms.
[22:07:41][VV][api.service:522]: on_hello_request: HelloRequest {
[22:07:41] …
```
> Increase cli tool logging timestamps to include nanoseconds

- aioesphomeapi/log_runner.py
This allows the `zeroconf` logic to work to watch for a device to come back online after it goes offline when an ip is passed to connect
It also gives a nicer output
```
INFO Reading configuration winefridge.yaml...
INFO Starting log output from 192.168.214.210 using esphome API
INFO Successfully connected to winefridge @ 192.168.214.210 in 0.021s
INFO Successful handshake with winefridge @ 192.168.214.210 in 0.043s
```
vs
```
INFO Reading configuration winefridge.yaml...
INFO Starting log output from 192.168.214.210 using esphome API
INFO Successfully connected to 192.168.214.210 in 0.021s
INFO Successful handshake with 192.168.214.210 in 0.043s
```
> Add the ability to pass the name the reconnect logic when running logs

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- tests/test__frame_helper.py
Since we set `TCP_NODELAY` it means all packets get written to the wire as soon as the buffer has space which means they get written almost right away in most cases. When we know we need to send multiple packets there was no way to send them in one write which increased protocol latency. To fix this write_packet is now write_packets which will do the write to the transport in a single go which increases the change the ESP will not have to transfer data from the stack multiple times to read incoming data.
> Refactor frame helper to allow sending multiple packets at once

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- tests/test__frame_helper.py
- tests/test_connection.py
Since frame helper know about the `APIConnection` object now it can stay in native code the whole time to call the `process_packet` and `report_fatal_error` functions.  Its a bit more tight coupling but frame helper is already tightly coupled to connection and its all internal anyways.
This makes processing incoming packets ~21% faster
> Refactor frame helper to avoid py conversions when processing packets

- aioesphomeapi/connection.py
- tests/test_connection.py
If the ESP sends `DisconnectRequest` and shuts down the connection immediately before we can reply with `DisconnectResponse`, `expected_disconnect` could fail to be set because it was set after `DisconnectResponse` was sent.  I've never seen this actually happen but given the related issues below we should fix this race to eliminate it as a future problem.
related issues: https://github.com/esphome/issues/issues/4794 and https://github.com/esphome/issues/issues/5013
Although I don't think this will fix that problem since nobody reported that there was an error in the log about not being able to write the `DisconnectResponse`, but we should still fix this race.
> Ensure expected_disconnect is True when sending DisconnectResponse fails

- bench/raw_ble_plain_text.py
Unrelated to this PR, but it looks like we made them faster since they were added:
`python3 bench/raw_ble_plain_text.py`
original
Processed 3000000 bluetooth messages took 1.390175749998889 seconds
current
Processed 3000000 bluetooth messages took 1.0902630420023343 seconds
> Fix benchmarks not working after latest refactoring

- aioesphomeapi/client.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- tests/test_client.py
- tests/test_connection.py
- Adds cython typing to ConnectionParams dataclass as we could not do this before since it is only newly supported in cython 3
- Switch a few calls from `send_message` to `send_messages` to avoid calling the wrapper
- Make timeout a required arg for `send_messages_await_response_complex` since we previously had problems with the default value and all places are now passing a timeout
> Small cleanups to connection

- aioesphomeapi/connection.py
- tests/common.py
- tests/test__frame_helper.py
- tests/test_client.py
- tests/test_connection.py
- tests/test_log_runner.py
- Improve coverage for the frame helpers
- `APIConnectionError` was being raised intead of `SocketClosedAPIError` which made it harder to figure out why it failed
> Fix `eof_received` not raising SocketClosedAPIError

- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- tests/test_connection.py
With previous refactoring we no longer need this complexity. We never call `send_messages` during the connection set up anymore.
> Remove in_do_connect contextvar

- aioesphomeapi/host_resolver.py
The server name is deterministic so we can avoid zeroconf having to ask for it as it will try the wrong one first if we do not pass it in which will generate network traffic to ask a question that can never be answered.
This will speed up resolution as well
> Pass server name to zeroconf when known

- aioesphomeapi/host_resolver.py
- tests/test_host_resolver.py
This will only work if scope_id is an int, but at least we can fix that
> Ensure scope_id is preserved from zeroconf resolution on python versions that support it

- aioesphomeapi/reconnect_logic.py
- tests/test_reconnect_logic.py
We did not hold the lock while we ran the disconnect callback. Also it would not run if we were stopped and we disconnect which means that callers might not tear down things that were expected.
This likely was not an actual problem in production but we could have started to reconnect before the disconnect hook had finished
> Fix race running disconnect callback in reconnect logic

- tests/test_client.py
The test is marked as xfail since there is currently a race that needs to be fixed
> Add test coverage for bluetooth GATT notify

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- tests/conftest.py
- tests/test_client.py
There was a race where we could miss a GATT notify response data if it was received in the same packet as the gatt notify response because the ESP was buffering the api reply because we did not install the listener before calling the subscribe
> Fix missed GATT notify if the device responds immediately after subscribe

- aioesphomeapi/client.py
We used to have to check all the message types when we got a callback because the callbacks would get delivered for everything. Since connection only delivers callbacks for ones we register for now, we still had some of the legacy pattern sitting around that needed to be cleaned up.
> Remove unneeded local variables from previous refactoring

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
- aioesphomeapi/connection.py
- bench/raw_ble_plain_text_with_callback.py
- tests/test__frame_helper.py
We did multiple checks to see if debug logging was enabled, but the connection already knows before it hands off to the frame helper.
Doing debug logging of raw packets is a bit questionable since the checks are high volume, but we have always done it so I'm hesitant to remove it
> Refactor frame helper to get debug state from connection

- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.py
- tests/test__frame_helper.py
We didn't set the future exception when there was fatal error in the frame helper so the caller would not get a good error when the connection was closed because the ESP does not use encryption but we were trying to anyways
> Fix handshake getting the wrong exception when the ESP drops the connection because its not using noise

- aioesphomeapi/_frame_helper/noise.py
- tests/common.py
- tests/conftest.py
- tests/test__frame_helper.py
- tests/test_client.py
- tests/test_connection.py
- tests/test_log_runner.py
We need to send the hello as soon as the connection is connected, otherwise the connection could already be closed by the time we start the handshake and we will not handle the error correctly.
Mocking `data_received` was not good enough because it was not wrapped in an exception check that would call `connection_lost` on error. The tests now work much more like production
> Fix error in noise frame helper were we could write when the writer was unset

- tests/test__frame_helper.py
This means we now have 100% coverage on all the frame helpers
> Add test for corrupt or invalid encryption

- aioesphomeapi/_frame_helper/plain_text.pxd
#692 introduced a regression because it did not treat the bytes as unsigned
> Fix signedness with incoming plaintext data

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
- tests/test__frame_helper.py
- Rename `_read_exactly` to `_read` since we only have one read function now
- adds more cython typing
> Optimize the frame helpers by improving cython typing

- aioesphomeapi/client.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- tests/common.py
- tests/test_connection.py
- tests/test_reconnect_logic.py
Because the on_stop happens in a task it has to wait one event loop iteration to remove the connection from the client
> Fix race in cleaning up connection

- aioesphomeapi/client.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- tests/conftest.py
- tests/test__frame_helper.py
- tests/test_client.py
- tests/test_connection.py
This should only be a breaking change for HA (we can avoid actually breaking anything by flipping the flag when HA changes the logging)
fixes #699
Testing
> Avoid expensive debug logging checks in packet processor

- aioesphomeapi/connection.py
self.is_connected will always be false because both of these functions run on a timer that is always cancelled in the same as the place where self.is_connected is flipped and since there are no awaits there is no race, and no need for this check
> Remove unreachable code in connection

- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
All of the calls come from client code which is internal and since we never manually construct protobuf messages it would not be possible to try to send one that did not exist. Instead we should raise KeyError since this would be a refactoring error during development and would never actually happen in production
> Remove unreachable check in connection send_messages

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- tests/test_client.py
- tests/test_connection.py
nothing was being awaited, this does not need to be a coro
> Make force_disconnect a normal function

- aioesphomeapi/connection.py
https://learn.microsoft.com/en-us/windows-hardware/drivers/network/so-rcvbuf is available in windows vista and later so its a bit unlikely someone will be using this library on windows pre-vista
> Remove unreachable socket buffering check code in connection

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- aioesphomeapi/core.py
- tests/conftest.py
- tests/test_client.py
The connection object was wrapping every non APIConnection exception as `APIConnectionError` but it should have wrapped it as `UnhandledAPIConnectionError` otherwise we will downgrade it to debug logging.
There may be some side effects here: Anything we think we were handling will now show as `logging.ERROR` instead of  `logging.DEBUG` or `logging.WARNING`. This is a good thing but it may cause users to create issues, but they will be for legitimate bugs in our connection handling
> Fix client connection code swallowing unhandled exceptions as debug logging

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
There were a few places we know all the args so there is no need to call the setter over and over as they can be set in the constructor
> Cleanup protobuf object construction

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
- tests/test__frame_helper.py
python3 bench/raw_ble_plain_text.py 
before
```
Processed 3000000 bluetooth messages took 1.0178361660218798 seconds
```
after
```
Processed 3000000 bluetooth messages took 0.5595999580109492 seconds
```
> Refactor reading varuints to significant simplify plaintext frame helper

- aioesphomeapi/reconnect_logic.py
- aioesphomeapi/zeroconf.py
- tests/test_reconnect_logic.py
If the address passed was just the name of the device without `.local.`, the reconnect logic could not find it
> Fix name logic with reconnect logic when APIConnection address lacks local

- aioesphomeapi/host_resolver.py
- aioesphomeapi/zeroconf.py
If the device is offline and we are watching for zeroconf records, avoid closing the zeroconf instance in the host resolver
> Avoid churning zeroconf instances in the host resolver when created in the reconnect logic

- aioesphomeapi/reconnect_logic.py
- tests/test_reconnect_logic.py
Because we cannot remove the listener until the next iteration of the event loop we would sometimes schedule multiple reconnect attempts from the records
fixes
```
DEBUG Can't connect to ESPHome API for picoproxy @ 192.168.211.138: Error resolving IP address: [Errno 8] nodename nor servname provided, or not known (APIConnectionError)
DEBUG Retrying picoproxy @ 192.168.211.138 in 19.00 seconds
DEBUG Scheduling new connect attempt in 19.00 seconds
DEBUG Trying to connect to picoproxy @ 192.168.211.138
DEBUG Connected lock acquired for picoproxy @ 192.168.211.138
DEBUG Resolving host picoproxy._esphomelib._tcp.local. via mDNS
DEBUG picoproxy @ 192.168.211.138: Triggering connect because of received mDNS record record[ptr,in,_esphomelib._tcp.local.]=4500.0/4500,picoproxy._esphomelib._tcp.local …
```
> Fix race scheduling reconnect from zeroconf records

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
Avoids a few more jumps back into python
Its a tiny speed up
Processed 3000000 bluetooth messages took 0.5272852919879369 seconds
> Small cython cleanps to the frame helpers

- aioesphomeapi/client.py
- aioesphomeapi/client_callbacks.pxd
- aioesphomeapi/client_callbacks.py
- tests/test_client.py
- The `on_bluetooth_connection_state` callback would still be called with `connected=False` if connecting timed out even though we raised `TimeoutError` because we called `_bluetooth_device_disconnect_guard_timeout` which also causes the ESP to send back `BluetoothDeviceConnectionResponse` before unsubbing the message listener so it would leak to the original caller.
- remove unreachable code. There was a check for KeyError and ValueError which are now impossible
> Fix races in bluetooth device connect

- aioesphomeapi/discover.py
```
File "src/zeroconf/_services/__init__.py", line 56, in zeroconf._services.Signal.fire
File "/opt/homebrew/lib/python3.11/site-packages/aioesphomeapi/discover.py", line 47, in async_service_update
print(FORMAT.format(state, short_name, address, mac, version, platform, board))
```
> Fix discover cli tool when address is missing from mdns

- aioesphomeapi/client.py
For protobuf messages we want to check the actual type instead of isinstance as we mean the actual message type and nothing else
> Use explict type checks for protobuf messages

- aioesphomeapi/client.py
We had duplicate logic here now that we have a way to create background task we can do them all the same way
> Use background task logic for the on_stop callback

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
There were two try blocks to convert exception types. Simplify by removing one of the try blocks and converting the exceptions in the connection class
> Small speed up to writing outgoing packets

- requirements.txt
0.128.4 has some significant bug fixes and the current requirement of 0.36.0 is missing some calls in ServiceInfo that we currently call so it does not work
> Bump zeroconf to >=0.128.4,<1.0

- aioesphomeapi/client.py
- aioesphomeapi/connection.py
- aioesphomeapi/host_resolver.py
- requirements.txt
- tests/conftest.py
- tests/test_client.py
- tests/test_connection.py
- tests/test_host_resolver.py
- tests/test_log_runner.py
- tests/test_reconnect_logic.py
Adds Happy Eyeballs support (https://datatracker.ietf.org/doc/html/rfc8305)
--
This PR is a first step as I need to make sure this library works for the other projects as well. Its likely to sit for a bit while I test the library with all the projects that need it so there aren't any need to do breaking changes before all the other projects start consuming it:
- https://github.com/aio-libs/aiohttp/pull/7954
- https://github.com/Jc2k/aiohomekit/pull/349
--
replaces and closes #233
> Add happy eyeballs support (RFC 8305)

- .github/workflows/ci.yml
- aioesphomeapi/client.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- aioesphomeapi/host_resolver.py
- aioesphomeapi/util.py
- tests/conftest.py
- tests/test__frame_helper.py
- tests/test_client.py
- tests/test_connection.py
- tests/test_host_resolver.py
If we have multiple IP addresses for the ESPHome device, and we do not know which one we should connect to, they should be passed as `addresses` when creating the `APIClient`
Tweaks Happy Eyeballs delay to 0.1s since we expect its local
> Add support for passing multiple addresses to the client

- aioesphomeapi/client.py
- aioesphomeapi/client_callbacks.py
- tests/test_client.py
Currently we only pass a `list` of `BluetoothLERawAdvertisement` back to the callback, which makes it difficult to change without a breaking change later when we need to add more information about the adv (such as BLE version, etc). 
Instead we now pass the `BluetoothLERawAdvertisementsResponse` object. 
This means we leak the abstraction a bit more, but considering how tightly coupled this all is, that seems like a good trade off to avoid a future breaking change (which is very likely coming with esp-idf 5.x at some point if we add support for extended advertising) now that we will use this in `bleak-esphome` and likely more places.
> Refactor raw Bluetooth advs subscriptions

- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- tests/test_connection.py
> Make failure to increase the recv buffer size non-fatal

- requirements.txt
cryptography 42+ has a breaking change for chacha20poly1305-reuseable so it must be >=0.12.1
HA issue https://github.com/home-assistant/core/issues/109804
esphome will likely have the same problem so lets fix it here
> Pin cryptography and chacha20poly1305-reuseable to minimum compatible versions

- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- requirements.txt
- tests/test__frame_helper.py
- tests/test_connection.py
- tests/test_log_runner.py
We end up creating a lot of tasks when the device is in deep sleep since its trying to reconnect.  We can replace them with `async_interrupt` and futures. This simplifies the connection process and reduces the chance for races.
This also speeds up connections because we don't end up with 3 tasks to make a connection anymore, only 1
> Avoid creating tasks for starting/finishing the connection

- aioesphomeapi/client.py
- aioesphomeapi/log_runner.py
- tests/test_client.py
- tests/test_log_runner.py
These functions no longer need to be coroutines since there is nothing to be awaited. The protocol does not ACK any of these requests (the connection will drop if there is a failure) so there is no need to make them awaitables
> Convert functions that no longer await to be normal functions

- Dockerfile
A small development improvement when using devcontainers so that the files are not saved by root, but your local user id correctly.
> Add esphome user to container

- aioesphomeapi/client.py
- tests/test_client.py
When a command was called and the connection was lost we did not raise a useful error for service calls and some of the command calls.
fixes #839
> Ensure all command and service calls raise when disconnected

- tests/conftest.py
- tests/test_client.py
- tests/test_log_runner.py
- tests/test_reconnect_logic.py
> Use loopback address in all tests

- aioesphomeapi/reconnect_logic.py
- requirements.txt
- tests/test_reconnect_logic.py
[0.132.1 fixes the problem with removing a listener from inside a listener](https://github.com/python-zeroconf/python-zeroconf/pull/1370)
HA has already bumped zeroconf. [Should wait to merge for esphome to bump it as well](https://github.com/esphome/esphome/pull/6548)
> Remove zeroconf listener removal workaround

- tests/test_connection.py
name is broken as a param to auto_spec in cpython 3.12.4 see https://github.com/python/cpython/issues/120732
fixes #889
> remove name from test auto_spec to workaround py3.12.4 breaking changes

- .github/workflows/ci.yml
We are a bit behind on updating the python version for the checks as 3.13 is nearly out.
> Run checks on python 3.12

- .github/workflows/ci.yml
- aioesphomeapi/client.py
- aioesphomeapi/reconnect_logic.py
- aioesphomeapi/util.py
- tests/test_reconnect_logic.py
- tests/test_util.py
We create tasks within tasks to connect which adds a bit of latency. We can avoid this with eager tasks. We still end up with the happyeyeballs overhead but that can be improved once cpython fixes some of the bugs in `asyncio.staggered` (See https://github.com/aio-libs/aiohttp/issues/8599)
> Add support for creating eager tasks to reduce connect latency

- requirements_test.txt
this project uses unittest.mock from the standard library
> remove extraneous dependency on old "mock"

- aioesphomeapi/client.py
- aioesphomeapi/client_callbacks.py
Added in #923 was the once flag, but I forgot to make a way for the clients using this library to be notified about this as the message itself is not passed outside the library.
> Adjust `subscribe_home_assistant_states` to allow separate callback

- aioesphomeapi/client_callbacks.py
- tests/test_client.py
Forgot this should be an `else`.
Didnt realise until I decided to add some logging to ha core that it was calling both still.
> Dont call subscription callback when we want single state only

- aioesphomeapi/connection.py
- tests/test__frame_helper.py
- tests/test_connection.py
There is a bug in protobuf with __str__ on a msg that can cause a crash
> Fix crash on Windows when debug logging is enabled

- .github/workflows/ci.yml
- aioesphomeapi/connection.py
https://github.com/esphome/aioesphomeapi/pull/932 proposed to use a new socket flag. Its likely this flag does not work on some operating systems that we support, but since we are not testing on them, its non-obvious if it will break or not.
> Ensure we are testing on MacOS and Windows

- aioesphomeapi/connection.py
Looking at network traces (on windows), the ESP responds with more data within 20ms to every TCP ACK of an API packet, but the python API consumer doesn't set the proper socket option to disable delayed ack and so windows delays for 40-50ms before sending an ack back.
Delayed ack waits for more data so multiple packets can be acked at the same time, which in most circumstances would be more efficient, except the esp has limited buffer space and must retain the tcp send buffer in case a retry is required if the packet doesn't get acked at all, so by disabling delayed ack on the other side of the API connection, packets can be acked immediately and this loop can be reduced to 1/2 to 1/3rd of it's current latency allowing 2-3x the send buffers to be dispatched over the TCP connection
This …
> Try to set TCP_QUICKACK where support for that option is available

- .pre-commit-config.yaml
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
Wrap the rust object in a cython wrapper to avoid multiple levels of useless checks to see if there is a key for every packet since we know there always well be.
> Speed up decrypting frames

- aioesphomeapi/client.py
- tests/test_client.py
The `VoiceAssistantAnnounceFinished` message is sent whenever the media player finished playing a TTS response (either from a pipeline or from an announcement). This message is automatically caught inside `send_voice_assistant_announcement_await_response`, which lets us know when the announcement is finished. But we won't know when a TTS response is finished without an additional callback (added here in this PR).
Unfortunately, we can't just watch the state of the media player in HA because:
1. If music is already playing, we will just see `PLAYING`
2. If the ESPHome media player is internal, we won't see it in HA
> Add handle_announcement_finished callback

- aioesphomeapi/client.py
- tests/test_client.py
We need to be able to distinguish between a pipeline ending because of on-device VAD and being cancelled/aborted because of a new wake-up or button press.
This PR splits these two cases apart as:
* `VoiceAssistantCommand(start=False)` aborts the pipeline (calls `handle_stop(abort=True)`)
* `VoiceAssistantAudio(end=True)` stops the pipeline by ending the audio stream (calls `handle_stop(abort=False)`)
> Interpret VoiceAssistantCommand(start=False) as abort

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/_frame_helper/plain_text.py
- tests/common.py
- tests/test__frame_helper.py
- tests/test_client.py
- tests/test_connection.py
With Python 3.12+ and later `transport.writelines` is implemented as [`sendmsg(..., IOV_MAX)`](https://github.com/python/cpython/issues/91166) which allows us to avoid joining the bytes and sending them in one go.
Older Python will effectively do the same thing we do now `b"".join(...)`
> Implement zerocopy writes

- aioesphomeapi/_frame_helper/noise.py
https://github.com/home-assistant/core/issues/131769
`2024-11-27 22:07:37.884 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.13/site-packages/noise/backends/default/ciphers.py:13: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in staticmethod() if you want to preserve the old behavior `
> Wrap PACK_NONCE in staticmethod

- requirements.txt
Most downstream is using protobuf 5 and protobuf only supports one version behind.
As a result we see broken cases like https://github.com/home-assistant/core/issues/129052 https://github.com/home-assistant/core/issues/130169
> Bump protobuf requirement to >=4

- .github/workflows/release.yml
The check should have been for musllinux instead of musl
> Fix CIBW_SKIP for musllinux in the release workflow

- requirements/base.txt
Significant bug fixes for the cache that will reduce the dashboard mDNS traffic
changelog: https://github.com/python-zeroconf/python-zeroconf/compare/0.132.2...0.143.0
> Bump zeroconf requirement to 0.143.0

- tests/benchmarks/test_requests.py
https://github.com/protocolbuffers/protobuf/blob/243b023c4530c1349437f036feb96cd053c0a8b2/python/convert.c#L192 seems to be called when setting bool and it takes an much longer than expected time. Might be a bug in protobuf
> Add more sending benchmarks

- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/core.py
- tests/test__frame_helper.py
We should not see an encryption error after unless the data is corrupted on the wire or there is memory corruption on the ESP, apparently this can happen.  While everything worked OK, the exception reached all the way into asyncio internals so its better to handle it internally.
fixes #1044
> Handle late encryption error

- aioesphomeapi/connection.py
- aioesphomeapi/host_resolver.py
- requirements/test.txt
- tests/conftest.py
- tests/test_connection.py
We can skip all the work to set up zeroconf if we already have IPs
> Avoid resolver overhead when all address are already IPs

- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- aioesphomeapi/core.py
- aioesphomeapi/host_resolver.py
- aioesphomeapi/util.py
- tests/conftest.py
- tests/test_client.py
- tests/test_connection.py
- tests/test_host_resolver.py
- tests/test_util.py
If the system doesn't support mDNS, or mDNS will take more time than the timeout to respond, we would never try DNS.  Instead we now resolve mDNS and DNS in parallel.
Additionally we had a 30s timeout to resolve, but the mDNS timeout was only 3s so we would end up timing out too quickly.
Sadly this is a lot more complex than I would like because we support resolving any number of host names at the same time so we can potentially have `X hosts` * `X IPs` results.
> Resolve hosts in parallel

- tests/test_client.py
When running the tests in an environment that uses network sandboxing using a random IP address causes issues, because it causes routing errors.
Same as #841
> Test against loopback address

- aioesphomeapi/discover.py
Fixes
```
File "/usr/local/lib/python3.11/dist-packages/aioesphomeapi/discover.py", line 47, in async_service_update
print(FORMAT.format(state, short_name, address, mac, version, platform, board))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to NoneType.__format__
```
reported at https://github.com/esphome/issues/issues/6311#issuecomment-2607087703
> Fix discovery display when values are unexpectedly empty

- aioesphomeapi/client.py
- tests/test_client.py
`subscribe_logs` calls did not have a way to cancel the subscription.
> Add the ability to cancel subscribe_logs

- aioesphomeapi/connection.py
When running on FreeBSD in Linux compatibility mode `sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_QUICKACK, 1)` throws `OSError`, not `AttributeError`.
> Also catch OSError when trying to set TCP_QUICKACK

- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
The `PyUpb_Message_GetAttr` looks a bit heavy because it looks in the message first and falls back to finding `MergeFromString`. It make sense to do it only once per message type. Its a bit unexpected that protobuf implemented this as a lookup for a known method.
> Avoid protobuf lookup to find MergeFromString

- README.rst
- aioesphomeapi/discover.py
This might help track down https://github.com/esphome/issues/issues/6311
Running with `aioesphomeapi-discover --verbose` will show all the mDNS traffic as well
> Add --verbose flag to aioesphomeapi-discover

- README.rst
The readme code for  `subscribe_states` causes error `TypeError: Object nontype can't be used in 'await' expression` because it is no longer [async](https://github.com/esphome/aioesphomeapi/commit/23a2f402fafa795aa1695592485662c9f6376e6b#diff-753f76689d07a39d2daa897bd6416dcb0546b60d15c3a944768fa4b8a75fd869R413-R423).
I updated the example code by removing `await`
> Update subscribe_states example in README

- tests/benchmarks/test_bluetooth.py
The current BLE benchmark didn't use real data. This version uses a real advertisement group
> Add additional BLE benchmarks

- tests/benchmarks/test_bluetooth.py
We didn't have a benchmark for multiple protobuf messages in a single read (data_received) call.
> Benchmark getting multiple protobuf messages in a single read

- .pre-commit-config.yaml
- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
`__Pyx_PyBytes_AsString` -> `__Pyx_PyBytes_FromStringAndSize` is significantly faster than `PySequence_GetSlice` and since we already have a bounds check with `if self._buffer_len < new_pos:` we don't need to worry about reading past the buffer.
Note that we have no benchmark for noise protocol so we need to add some before merging this PR to validate the improvement
The speaker buffer looks to be about 16KiB from `esphome/components/voice_assistant/voice_assistant.cpp` so it should help that as well
> Improve buffer read performance

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/connection.pxd
`except *` should be added to the pxd for Cython void functions that can raise an exception
> Ensure all void functions that can raise are properly marked

- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
Cython can better optimize `b""` since it doesn't have to ref count it
> Remove unneeded EMPTY_PACKET constant in plain_text frame helper

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
Add cdef for _handle_error_and_close in the frame helper
Subclasses never need to override this so it can be a cdef
> Add cdef for _handle_error_and_close in the frame helper

- aioesphomeapi/client.py
- aioesphomeapi/reconnect_logic.py
Remove redundant casts to int from round
Found by ruff 0.1.0
> Remove redundant casts to int from round

- aioesphomeapi/reconnect_logic.py
- tests/test_reconnect_logic.py
We should kick start the reconnect logic when getting an AAAA record in addition to the existing A and PTR logic
> Add IPv6 support to the reconnect logic zeroconf listener

- aioesphomeapi/__init__.py
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/core.py
- tests/test__frame_helper.py
We need a way to tell when encryption is no longer being used
in Home Assistant
https://github.com/home-assistant/core/issues/121442
> Raise EncryptionHelloAPIError when connection drops during encrypted hello

- aioesphomeapi/__init__.py
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/core.py
- tests/test__frame_helper.py
related issue https://github.com/home-assistant/core/issues/142381
- esphome/esphome#https://github.com/esphome/esphome/pull/8521
> Raise EncryptionPlaintextAPIError when noise is selected but remote protocol is plaintext

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
Only convert the bytes object to a cstr once before the loop.
> Improve performance of reading varuints

- aioesphomeapi/_frame_helper/base.pxd
- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/_frame_helper/plain_text.pxd
- aioesphomeapi/_frame_helper/plain_text.py
Only plaintext reads varuints on the wire, this should be in plaintext and not base
> Relocate _read_varuint from base to plaintext framehelper

- aioesphomeapi/__init__.py
- aioesphomeapi/_frame_helper/noise.pxd
- aioesphomeapi/_frame_helper/noise.py
- aioesphomeapi/client.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- aioesphomeapi/core.py
- tests/benchmarks/test_noise.py
- tests/common.py
- tests/test__frame_helper.py
needs https://github.com/esphome/esphome/pull/8551
We currently only have the ability to check for an expected name, but we need to be able to check for an expected mac as well to know we are talking to the expected device.
related issue https://github.com/home-assistant/core/issues/133956
- esphome/esphome#8551
> Add check for unexpected MAC address for noise protocol

- aioesphomeapi/_frame_helper/base.py
- aioesphomeapi/client_base.py
- aioesphomeapi/connection.py
- aioesphomeapi/reconnect_logic.py
- pyproject.toml
- tests/benchmarks/test_bluetooth.py
- tests/benchmarks/test_noise.py
- tests/conftest.py
- tests/test__frame_helper.py
- tests/test_client.py
- tests/test_connection.py
- tests/test_host_resolver.py
- tests/test_log_runner.py
- tests/test_model.py
- tests/test_reconnect_logic.py
- tests/test_util.py
- tests/test_zeroconf.py
Calling `get_event_loop` with no running loop emits a warning, in a future Python version it will be an error. Make sure we are not using it.  This is a breaking change because it would create an event loop if one was not running. Spontaneous event loop creation is generally considered a bad thing which is why its deprecated in Python itself. Someone could be expecting it to work though so we will increment the major version.
> https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop
> Replace get_event_loop with get_running_loop

- aioesphomeapi/client_base.py
- tests/test_client.py
The Cython type was too strict here : https://github.com/esphome/esphome/pull/8576#issuecomment-2808000287
> Ensure set_cached_name_if_unset accepts subclassed str

- aioesphomeapi/_frame_helper/noise_encryption.pxd
- tests/benchmarks/test_noise.py
- tests/common.py
- tests/test__frame_helper.py
The benchmarking wasn't using the actual path we use and was using the slow wrapper
> Improve encrypt benchmarking

- tests/benchmarks/test_noise.py
Most messages are ~64-128 bytes (or smaller).  Our benchmarks were targeting far too large of payloads
> Add benchmark for most frequent noise message sizes

- tests/test_model.py
We missed legacy brightness in the protobuf sync. Ensure we have coverage for it.
> Add coverage for parsing legacy brightness

- aioesphomeapi/connection.py
- tests/test_connection.py
This PR fixes a race condition where internal message handlers were registered too late, causing early internal messages to be dropped during connection setup.
When establishing a connection, the internal message handlers (for DisconnectRequest, PingRequest, and GetTimeRequest) were being registered after the frame helper was initialized. Since the frame helper starts receiving traffic immediately upon initialization, any internal messages received before handler registration would be lost.
Moved the `_register_internal_message_handlers()` call to occur before `_connect_init_frame_helper()` in the `_do_finish_connect` method. This ensures handlers are ready before any network traffic can be received.
Added `test_internal_message_received_immediately_after_connection` which:
- Simulates …
> Fix race condition with internal message handlers registration

- aioesphomeapi/__init__.py
- aioesphomeapi/log_parser.py
- aioesphomeapi/log_reader.py
- setup.py
- tests/test_log_parser.py
This PR adds support for properly formatting multi-line log messages from ESPHome devices. ESPHome will be able to minimize network overhead by sending multi-line log entries as single protobuf messages with embedded newlines, rather than splitting them into multiple messages. This is efficient for the network and the ESP device (which has limited resources), but requires the client to properly format these messages for human consumption.
The new log parser:
- Preserves timestamps, log level prefixes, and component names across continuation lines
- Maintains ANSI color codes throughout multi-line messages
- Prevents color bleeding by adding proper reset codes
- Optimizes for the common single-line case (11M ops/sec)
Example - Before:
```
[08:00:00.000][C][template.sensor:022]: Template …
```
> Add support for rendering multi-line log messages

- aioesphomeapi/client_base.py
- tests/test_client.py
We need a broad exception catch around the callback since it calls back into third party code which may raise up to the protocol handler and disconnect the device.
> Ensure third party callbacks on BLE notify do not cause disconnect

- aioesphomeapi/model.py
- tests/test_model.py
This PR fixes an issue with `DeviceInfo` round-trip serialization that was introduced when the `areas`, `devices`, and `area` fields were added in #1146. 
When using `DeviceInfo.to_dict()` followed by creating a new `DeviceInfo` instance from that dictionary (a common pattern for mocking in tests), the code would fail with an `AttributeError` because the `area` field converter expected a protobuf object but received a dictionary.
The fix adds a `convert` method to `AreaInfo` that properly handles both dictionary and protobuf inputs, similar to how the `convert_list` methods already work for the list fields.
- fixes round-trip serialization issue introduced in #1146
**Pull request in [esphome](https://github.com/esphome/esphome) (if …
> Fix DeviceInfo round-trip serialization after areas/devices fields additions

- aioesphomeapi/model.py
Noticed in https://github.com/esphome/backlog/issues/1#issuecomment-3009670879
> Add missing field to model.py

- aioesphomeapi/connection.py
- tests/test_connection.py
- tests/test_log_runner.py
This PR implements pre-work for #1246 by modifying the connection logic to skip waiting for `ConnectResponse` when no password is configured, while still handling unexpected password responses gracefully.
When connecting to a passwordless ESPHome device, we now:
1. Only wait for `ConnectResponse` if we actually have a password to send
2. Register a handler for `ConnectResponse` messages that arrive unexpectedly
3. Report authentication errors if a device requires a password but we don't have one
This provides an immediate performance benefit for passwordless connections while maintaining backward compatibility and robust error handling.
- Pre-work for #1246
- …
> Skip waiting for ConnectResponse when no password is configured

- aioesphomeapi/connection.py
- tests/test_connection.py
This PR fixes an IndexError that occurs when `login=False` but `password=None` in the `_connect_hello_login` method. Previously, the code would attempt to pop a `ConnectResponse` from an empty responses list, causing the connection to fail.
The fix adds a proper guard to only pop the login response when both `login` is True AND a password is configured (`has_password` is True).
This regression was introduced in #1276 where the pop logic was updated to check `has_password`, but it missed also checking the `login` parameter, causing it to still attempt to pop when `login=False`.
- fixes IndexError when connecting with login=False and password=None
- N/A
> Fix IndexError when connecting with login=False and password=None

- aioesphomeapi/connection.py
- tests/test_connection.py
This is a follow-up to PR #1267 which downgraded `APIConnectionCancelledError` log level to DEBUG in `reconnect_logic.py`. 
This PR applies the same fix to `connection.py`'s `report_fatal_error` method, which was logging the same harmless cancellation errors at WARNING level. It was observed that these warnings appear during ESPHome OTA updates:
```
WARNING maui_es015_tb_b @ 192.168.106.162: Connection error occurred: Error while starting connection: Starting connection cancelled
```
These cancellation errors are expected behavior when connections are intentionally cancelled and should not be logged at WARNING level.
- Follow-up to #1267
- N/A
> Downgrade APIConnectionCancelledError log level to DEBUG in connection.py

- aioesphomeapi/client.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- aioesphomeapi/reconnect_logic.py
- tests/test_client.py
- tests/test_connection.py
This PR fixes an issue where connection errors are logged twice when ESPHome devices are offline and reconnect_logic is being used. Currently, both the `connection.py` layer and `reconnect_logic.py` layer log the same errors, resulting in log spam with potentially different log levels.
The solution adds a `log_errors` parameter to APIConnection that allows reconnect_logic to disable the connection layer's internal error logging. This ensures that:
- When using reconnect_logic: Only reconnect_logic logs errors (WARNING for first attempt, DEBUG for retries)
- When using direct connections: connection.py still logs errors normally
- No duplicate logging between the two layers
- fixes https://github.com/home-assistant/core/issues/149775
**Pull …
> Prevent duplicate connection error logging when using reconnect_logic

- aioesphomeapi/client_base.py
- tests/test_client.py
This PR fixes a TypeError that occurs when ESPHome passes `Estr` (subclassed string) objects in the `addresses` parameter to the APIClient. The fix ensures all address strings are properly converted to regular Python `str` objects before being used.
- fixes TypeError: Expected str, got EStr when using multiple addresses
- N/A (This is a client-side fix for handling ESPHome's string types)
The issue occurs when ESPHome passes addresses as `Estr` objects (a subclassed string type used in ESPHome). While individual address parameters and other string parameters like `noise_psk` and `expected_name` were already being converted using `_stringify_or_none()`, the …
> Fix TypeError when addresses parameter contains Estr objects

- .github/workflows/release.yml
This PR fixes the wheel building configuration to stop producing Python 3.10 wheels. The project requires Python >=3.11 (as specified in setup.py), but the CI workflow was still building wheels for Python 3.10.
- N/A
- N/A
> Skip Python 3.10 wheel builds to match minimum Python requirement

- aioesphomeapi/client.py
- aioesphomeapi/connection.pxd
- tests/test_client.py
send_messages should have been cpdef so it was accessible via Python.
Rename subscribe_homeassistant_states_and_services to subscribe_home_assistant_states_and_services to be in line with other APIs
> Fix subscribe_home_assistant_states_and_services with Cython

- aioesphomeapi/api.proto
- aioesphomeapi/client.py
- tests/test_client.py
This PR makes `address_type` a required parameter for Bluetooth device connections by validating it is not `None` before attempting to connect. Previously, connections without an `address_type` would always fail on the ESPHome side, but now we raise a clear error immediately on the client side.
Additionally, this PR adds a deprecation comment for the `has_address_type` field in `api.proto`, marking it for removal in 2027.8 since `address_type` is now always required.
- Related to investigation of ble_client issues
- esphome/esphome#10318
This is not a breaking change because Bluetooth connections without `address_type` never worked properly - they would always …
> Validate address_type is provided for Bluetooth connections

- aioesphomeapi/client_base.py
- tests/test_client.py
Add support for getting the connected_address in the client
client.connected_address returns the currently connected address
> Add support for getting the connected_address in the client

- aioesphomeapi/client_base.py
- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- aioesphomeapi/timezone.py
- tests/common.py
- tests/test_client.py
- tests/test_timezone.py
This PR adds a `timezone` parameter to `APIClient` to allow Home Assistant to explicitly pass its configured timezone to ESPHome devices, ensuring ESPHome devices use Home Assistant's timezone rather than the container's timezone when they differ.
While this works correctly on Home Assistant OS, users who run Home Assistant in self-configured containers may set a `TZ` environment variable that differs from Home Assistant's configured timezone. Currently, the `tzlocal` library detects and uses the container's `TZ` environment variable, causing ESPHome devices to prefer the container-configured timezone over Home Assistant's configured timezone. This leads to scheduling issues when the two timezones don't match (e.g., sprinklers running at unexpected times).
The fix allows Home Assistant to …
> Add timezone parameter to APIClient to fix container timezone override issue

- aioesphomeapi/connection.py
- tests/test_connection.py
This PR fixes a segmentation fault that occurs when `send_messages()` is called after the connection has been cleaned up and `_frame_helper` has been set to None. The segfault was caused by a null pointer dereference in the Cython-compiled code.
The issue can manifest in various scenarios including:
- Authentication failures (wrong/missing password)
- Connection errors during operation
- Race conditions between cleanup and message sending
- Any situation where `report_fatal_error()` → `_cleanup()` is called while other operations are still attempting to send messages
The root cause is that `_cleanup()` sets `_frame_helper = None`, but `send_messages()` could still be called from various code paths (callbacks, pending operations, etc.) and would attempt to access `None.write_packets()` in …
> Fix segfault when send_messages is called after connection cleanup

- aioesphomeapi/connection.pxd
- aioesphomeapi/connection.py
- tests/test_connection.py
This PR fixes a connection timeout issue that occurs when a client with a configured password tries to connect to an ESPHome device that doesn't support password authentication.
Previously, when the client had a password configured but the device didn't support passwords, the connection would timeout after 30 seconds waiting for an `AuthenticationResponse` that would never arrive. This change modifies the connection flow to only wait for the `HelloResponse` and handle authentication responses asynchronously.
- fixes timeout error: `Timeout waiting for HelloResponse, AuthenticationResponse after 30.0s`
- N/A
The fix changes the `_connect_hello_login` method to: …
> Fix connection timeout when password is configured but device does not support authentication

- aioesphomeapi/connection.py
- tests/test_connection.py
Ensure fatal exception is logged when cleaning up
> Ensure fatal exception is logged when cleaning up
